name = "programas-fibra-tile-server"
main = "src/index.ts"
compatibility_date = "2024-09-02"
minify = false

r2_buckets  = [
  { binding = "BUCKET", bucket_name = "programas-fibra-geo" }
]

[vars]
PMTILES_PATH = "map.pmtiles"
ALLOWED_ORIGINS = "*"
